Sys.setenv(DO_PAT="b5ada2301098ccded2287430e4233b087140e96fbad7f2a2283c786a87cc734f")
library(analogsea)
# mydrop <- plumber::do_provision()
# 
# mydrop %>% debian_apt_get_install("libudunits2-dev")
# mydrop %>% debian_apt_get_install("libproj-dev")
# mydrop %>% droplet_ssh("sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable")
# mydrop %>% debian_apt_get_update()
# mydrop %>% debian_apt_get_install("libgdal-dev")
# mydrop %>% debian_apt_get_install("libv8-3.14-dev libprotobuf-dev protobuf-compiler")
# 
# mydrop %>% install_r_package("sf")
# mydrop %>% install_r_package("banR")
# mydrop %>% install_r_package("memoise")
# mydrop %>% install_r_package("tidyverse")
# mydrop %>% install_r_package("sp")
# mydrop %>% install_r_package("geojsonio")

mydrop <- droplet("59340474")
mydrop %>% plumber::do_deploy_api("cmarue", "./", port = 8001)
